export const categories = [
  {
    name: "Electronics & Gadgets",
    subcategories: [
      "Smartphones & Accessories",
      "Computers & Laptops",
      "Tablets & E-readers",
      "Cameras & Photography",
      "Audio Devices (Headphones, Speakers)",
      "Wearables (Smartwatches, Fitness Bands)",
      "Gaming Consoles & Accessories",
      "Drones & Action Cameras",
      "Home Appliances (Smart TVs, ACs, Refrigerators)",
      "Office Electronics (Printers, Scanners, Projectors)",
    ],
  },
  {
    name: "Fashion & Apparel",
    subcategories: [
      "Men's Clothing (Shirts, Trousers, Jackets)",
      "Women's Clothing (Dresses, Kurtis, Tops)",
      "Kids & Babies Clothing",
      "Shoes & Footwear (Casual, Formal, Sports)",
      "Accessories (Bags, Wallets, Belts, Sunglasses)",
      "Sportswear & Activewear",
      "Ethnic & Traditional Wear",
      "Jewelry (Fashion & Fine Jewelry)",
    ],
  },
  {
    name: "Home & Living",
    subcategories: [
      "Furniture (Beds, Sofas, Tables)",
      "Home Decor (Wall Art, Clocks, Lighting)",
      "Kitchen & Dining (Cookware, Utensils, Storage)",
      "Bedding & Bath (Bedsheets, Towels, Curtains)",
      "Storage & Organization",
      "Cleaning Supplies & Tools",
      "Smart Home Devices",
    ],
  },
  {
    name: "Health & Beauty",
    subcategories: [
      "Skincare & Haircare",
      "Cosmetics & Makeup",
      "Personal Care (Shaving, Oral, Feminine Care)",
      "Health Supplements & Vitamins",
      "Fitness Equipment",
      "Wellness & Spa Products",
      "Medical Supplies",
    ],
  },
  {
    name: "Grocery & Food",
    subcategories: [
      "Fresh Produce (Fruits & Vegetables)",
      "Dairy & Bakery",
      "Packaged & Processed Foods",
      "Beverages (Juices, Tea, Coffee, Soft Drinks)",
      "Snacks & Confectionery",
      "Organic & Specialty Foods",
      "Frozen & Ready-to-Eat Meals",
    ],
  },
  {
    name: "Sports & Outdoor",
    subcategories: [
      "Exercise Equipment (Treadmills, Dumbbells)",
      "Outdoor Gear (Camping, Hiking, Travel)",
      "Bicycles & Accessories",
      "Sports Apparel & Footwear",
      "Team Sports Equipment (Cricket, Football, Basketball)",
      "Water Sports Gear",
    ],
  },
  {
    name: "Automotive & Industrial",
    subcategories: [
      "Car Accessories (Covers, Seat Covers, Electronics)",
      "Motorbike Accessories (Helmets, Gloves, Gear)",
      "Car Care (Oils, Cleaners, Tools)",
      "Industrial Supplies & Tools",
      "Spare Parts",
    ],
  },
  {
    name: "Books, Music & Media",
    subcategories: [
      "Books (Fiction, Non-fiction, Academic)",
      "E-books & Audiobooks",
      "Music & Instruments (Guitars, Keyboards, Drums)",
      "Movies, Games & Collectibles",
      "Stationery & Office Supplies",
    ],
  },
  {
    name: "Toys & Kids",
    subcategories: [
      "Toys (Action Figures, Dolls, Cars)",
      "Educational Kits & STEM Toys",
      "Baby Gear (Strollers, Car Seats, Cribs)",
      "Outdoor Play (Slides, Swings, Trampolines)",
      "Board Games & Puzzles",
    ],
  },
  {
    name: "Pet Supplies",
    subcategories: [
      "Pet Food & Treats",
      "Pet Toys & Accessories",
      "Pet Grooming Products",
      "Health & Veterinary Care",
      "Aquarium & Bird Supplies",
    ],
  },
  {
    name: "Jewelry & Watches",
    subcategories: [
      "Watches (Smart, Luxury, Casual)",
      "Gold Jewelry",
      "Silver Jewelry",
      "Diamond Jewelry",
      "Fashion Jewelry",
      "Handmade Jewelry",
    ],
  },
  {
    name: "Travel & Luggage",
    subcategories: [
      "Suitcases & Trolleys",
      "Backpacks & Duffel Bags",
      "Travel Accessories",
      "Handbags & Wallets",
    ],
  },
  {
    name: "Office & Stationery",
    subcategories: [
      "Office Furniture",
      "Notebooks & Writing Supplies",
      "Art & Craft",
      "Printers, Ink & Supplies",
    ],
  },
  {
    name: "Services & Subscriptions",
    subcategories: [
      "Gift Cards",
      "Online Courses",
      "Software Subscriptions",
      "Streaming Services",
    ],
  },
];

export const categoriesResgiter = [
  "All",
  "Electronics & Gadgets",
  "Fashion & Apparel",
  "Home & Living",
  "Health & Beauty",
  "Grocery & Food",
  "Sports & Outdoor",
  "Automotive & Industrial",
  "Books, Music & Media",
  "Toys & Kids",
  "Pet Supplies",
  "Jewelry & Watches",
  "Travel & Luggage",
  "Office & Stationery",
  "Services & Subscriptions",
];

export const categoriesAnimation = [
  "Speakers",
  "Watch",
  "Earbuds",
  "Mouse",
  "Decoration",
  "Headphones",
  "Mobiles",
  "Tablets",
  "Accessories",
  "Laptops",
  "Cameras",
  "Gaming Consoles",
  "Smart Home",
  "Printers",
  "Monitors",
  "Furniture",
  "Clothing",
  "Shoes",
  "Beauty & Personal Care",
  "Sports & Fitness",
];
